name: Beaconator
version: '${version}'
main: net.azisaba.beaconator.Beaconator
api-version: '1.15'
author: albardoo02
description: A plugin that allows players to toggle potion buffs on themselves via a GUI.
commands:
  beacon:
    aliases:
      - petbeacon
      - petb
      - pb
      - buff
permissions:
  beaconator.level.apprentice:
  beaconator.level.adapt:
  beaconator.level.expert:
  beaconator.level.master: